// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Errors {
    error INSUFFICIENT_FUNDS();
    error INSUFFICIENT_WEARABLE();
    error INSUFFICIENT_AUTHORIZATION_OVER_TOKENS();
    error COST_TOO_LOW();
    error IDS_AND_QUANTITY_NEEDS_TO_BE_THE_SAME_LENGTH();
    error MAXIMUM_WEARABLE_LENGTH();
    error NOT_MODISHX_WEARABLE();
    error ITEM_HAS_NOT_BEEN_LISTED();
    error ITEM_HAS_BEEN_SOLD();
    error WEARABLE_HAS_ALREADY_BEEN_CANCELLED();
}
